Standard Lib ist numpy. 

In [1]:
import numpy as np


In [5]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
B = np.array([[1,2,3], [4,5,6]])
C = np.array([1,2,3, 4,5,6])


In [6]:
l_matrix = [A, B, C]

for i in l_matrix:
    print(f"Shape of matrix: {i.shape}")

Shape of matrix: (3, 3)
Shape of matrix: (2, 3)
Shape of matrix: (6,)


In [8]:
zeros = np.zeros((3, 4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
ones = np.eye(3)
print(ones)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
D = np.hstack((A, A))
print(A, '------', D)
print('------')
E = np.vstack((A, A))
print(A, '------', E)

[[1 2 3]
 [4 5 6]
 [7 8 9]] ------ [[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]
------
[[1 2 3]
 [4 5 6]
 [7 8 9]] ------ [[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
D.reshape(6, 3) 


array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [7, 8, 9],
       [7, 8, 9]])

Bibliothek Sympy

In [19]:
import sympy as sp

für Gauss-Jordan Verfahren müsen wir diese Lib verwenden, numpy hat das nicht. 